In [1]:
#### Python is a case senstive language####
name = 'my name is palash'
Name = "my name is xxx"
NAME = "mm"
print(name)
print(Name)


my name is palash
my name is xxx


In [3]:
###dynamic data type #####
a = True
type(a) # type function helps us to check the datatype of a variable

int

In [7]:
"""
The id() function returns a unique id for the specified object.

All objects in Python has its own unique id.

The id is assigned to the object when it is created.

The id is the object's memory address, and will be different for each time you run the program.
"""
###memory management####
x = 275
y = 275
print ("both are same "+ str(id(x))+ ' '+ str(id(y)))
# y = 6
# print ("both are not same "+ str(id(x))+ " " + str(id(y)))


both are same 3110859895984 3110859896176


In [ ]:
t=89
#help(t)
#dir(t)

In [8]:
### Printing a value with our own message###

Num = 50 #int
print("This is a number", Num)
Num1 = '53'
print('This is a number', Num1)
print(Num+int(Num1)) #type casting can help in changing the datatypes, Here + is used as addion operator
print(str(Num)+Num1) #type casting. Here + operator is used as concatenation

This is a number 50
This is a number 53
103
5053


In [10]:
print('palash\notes') # \n means a new line
print(r"palash\notes")

palash
otes
palash\notes


In [10]:
print("class doesn't have offline students")
print('class doesn\'t have offline students')
print('"class doesn\'t have offline students"')

class doesn't have offline students
class doesn't have offline students
"class doesn't have offline students"


In [ ]:
## deleting a variable###
w=7
print(w)
del w
#print(w)
#w = w+3
print('hi')

In [ ]:
####printing values in between a string####
Name = "Sachin"
Age = 35
print(f'My name is: {Name}, and my age is {Age}') # printing using f-string
y = f'My name is: {Name}, and my age is {Age}'
print(y)



In [ ]:
####printing values in between a string####
Name1 = "palash"
Age1 = 35
print('My name is: {}, and my age is {}'.format(Name1, Age1)) # string.format(arguments)
print('My name is: {0}, and my age is {1}'.format(Name1, Age1))#index-based format function
print('My name is: {b}, and my age is {a}'.format(a=Name1, b=Age1))# reference-based format function

In [11]:
### Field conversion####
x = 73 ## integer use %d
variable_a = 'H' ## use %c to print charecter
y = 33.98 ## for float Use %f
print("One is integer: %c and other float %f, and another charecter is %c"%(x,y,variable_a))

ascii_code = 'A'
v = ord(ascii_code) ## pass the paramenter and get its corresponding ascii value
print(ord(ascii_code))  # ord () can be used to get the corresponding ASCII value


One is integer: I and other float 33.980000, and another charecter is H
65


In [ ]:
name = "Palash"
name[5]

print(len(name)) # len() is system function  that return the number of charecter of a string
x = 10 * name
print(x)

In [ ]:
""""Write a python program to print your name sum of ascii char/length times. Make sure to print your name 
in a new line each time. 

Creat two files: assign1.txt {your program}
                 readme1.txt (explanation of your code)
                 keep this two files in a folder. name the folder with your name_roll. make a zip. 
                 and upload."""

In [ ]:
name = "Palash"
length = len(name)
sum = ord(name[0]) + ord(name[1])+ ord(name[2]) + ord(name[3])+ ord(name[4]) + ord(name[5])
print("The sum of ascii", sum)
d = (sum//length)
print("D:", d)
name  = name + '\n' # concatenation operator
y = d * name
print(y)
1st time: Palash + '\n'
2nd time: Palash + '\n'

In [18]:
#### List ########
#1. list are used to store multiple values in a single variable.
#2. List is a kind of data type, collection.
#3. List items are ordered (maintain sequence, indexing is available).
#4. List is mutable (changeable).
#5. It also allows duplicates.
#6. For creating a list, we will use square braces.

nums = [] # empty list
num1 = [25,12,36,95,14, 25, 25] # created a list of homogeneous values (int)
print(num1[-6])
#print(num1[1:5]) # accessing a portion of a list either by postive or by negative indexing
#print(num1[-5:]) 

name = ["Palash", "IITJ", "Sachin"] # list of strings
#print(name[1])

values = ["Palash", "35", "100000.667"] # we want to create a list of heteregenous data
values [0] = "John" # a list is mutable or changable.

mis = [nums, num1, name] # list of list or nested list
mis[2][2] # indexing is also possible in nested lists.
#########some function on a list ##################
num1.append(100) # append function is used to insert at the last of the list
num1.insert(1, 200) # using insert you can insert an element to desired location.
num1.remove(25) # remove fuction removes an element by its value and removes the first occurance.
num1.remove(25)
num1.pop(1) # pop is used to remove an element by the index value
num1.pop() # Pop with no index deletes form the last.
print(num1)
#del num1 [2:] # delete is used to delete a portion of a list [exact position: delete postion+1]
#print(num1) 
min(num1) # return the minimum
max(num1)
sum(num1)
num1.sort()


12
[200, 36, 95, 14, 25]


In [20]:
##### Tuple ###############
#1. single variable can store multiple data.
#2. It is also ordered.
#3. It is not mutable.
t = (23, 20, 6, 5,20) # tuple is created using the round braces (during creation, we should be careful about the braces).
print(t[2]) # Indexing is supported so it is ordered. For accessing, always use square braces.
type(t) # type is a library function so round braces.
#t[2] = 10   # tuples are not mutable or changable.
t1 = ("Palash", "35")
print(t.count(20)) # count is used to count the number occurances of a value.
print(t.index(6)) # index returns the first occurance of a value
t3 = (t, t1) # tuple of touples is also possible
print(t3[1][1])
ls=list(t)
print(ls)

6
2
2
35
[23, 20, 6, 5, 20]


In [26]:
#### Set #########
#1. A set is collection of unique elemnts.
#2. for creating a set we will use a curley braces.
#3. Set is not ordered.
s = {2,3,1,8,5,96} #  duplicates are not allowed in a set
s1 = {2,4,5,"palash"}
type(s)
print(s1.intersection(s))
s1.add(3)
s1.add(3)
print(s1) #Indexing is not allowed because it does not have any order.
print(list(s1))

{2, 5}
{2, 3, 4, 5, 'palash'}
[2, 3, 4, 5, 'palash']


In [29]:
########### Dictionary ##############
#1. creating dict we will use curley braces.
#2. Dict stores the key-value pairs.
#3. the keys are immutable and unique.

data = {1: "palash", 2: "john", 3: "hemangee"}
#print(data[3]) # accessing data is done based on the key value
#print(data.get(3, "Data not present"))
data [1] = "ABC"
print(data)
##### creating a dict from two lists #####
keys = ["Palash", "John", "Hemangee"]
values = ["CS", "Networks", "Maths"]
data1 = dict(zip(keys, values))# zip function and typecasting is used
print(data1)
##### creating a dict from two tuples #####
keys = ("Palash", "John", "Hemangee")
values = ["CS1", "Networks1", "Maths1"]
data2 = dict(zip(keys, values))# zip function and typecasting is used
print(data2)
##### creating a dict from two sets #####
keys = {"Palash1", "John1", "Hemangee1"}
values = {"CS1", "Networks1", "Maths1"}
data3 = dict(zip(keys, values)) # zip function and typecasting is used
#print(data3)
##### Complex and nested dictionary ######
city = {"High Court": 93256613621, "shopping mall": ['PVR', "City Center"], "restaurants":{"chinese": "yochina", "Indian":["BBQ","Kasturi"]}}
print (city["restaurants"]['Indian'][0])

{1: 'ABC', 2: 'john', 3: 'hemangee'}
{'Palash': 'CS', 'John': 'Networks', 'Hemangee': 'Maths'}
{'Palash': 'CS1', 'John': 'Networks1', 'Hemangee': 'Maths1'}
BBQ


In [ ]:
##### Conditional execution using If-else #######
a = 5
b = 41
if a<b:  # Boolean values can be used as conditiona as well# in case of python : is mandatory. If you keep any non-zero value that is evaluated as true.
    print("We are in if block") # intendentaion are used to create block or suite
    print("b is greater than a")
else :
    print("We are in else block")
    print("a is greater than b")
print("Out")


In [ ]:
x = 88
y = 8
if x < y:
    print("x is lesser than y")
if x!=y:
    print("x and y is not equal")
if x>y:
    print("x is greater than y")
else:
    print ("x and y is equal")
print("done!!!")

In [ ]:
x = 88
y = 8
if x < y:
    print("x is lesser than y")
elif x!=y:
    print("x and y is not equal")
elif x>y:
    print("x is greater than y")
else:
    print ("x and y is equal")
print("done!!!")

In [ ]:
####### nested if-else###########
name = "IITJ"
name1 = "AIIMs"
deptcode = 5 # assignment, meaning that we are storing the value in the variable
if name =="IITJ":
    if(deptcode == 1): # == is a conditional operator, we check whether the value of deptcode is 1
        print("CSE")
    elif(deptcode == 2):
        print("AID")
    else:
        print("NON Computer")
if name1 == "AIIMs":
    if(deptcode == 1):
        print("radiology")
    elif(deptcode == 2):
        print("cardilogy")
    else:
        print("General") 
print("thanks!!!")


In [ ]:
###### short hand if ############
# when you have only one statement you can use short hand if
# a = 50
# if a>10: 
#     print("Hey")
    
# b = 3
# print("hello") if b==2 else print ("hi") ## body of if is in the left and the the right.
a=4
b=3
if b==2: 
    print ("hello")
else:
    if (a==b):
        print ("hi")
    else: 
        print ("welcome")
        
print("hello") if b==2 else print ("hi") if (a==b) else print ("welcome")

In [ ]:
########### Loops #################
"""
A loop is a sequence of instructions that is continuously repeated untill a certail condition is reached.
Primaliry two loops:
1. for loop
2. while loop
"""
v_r = range(10) #The range is a built-in function that return a range object that consists of series of integers.
# print(type(v_r)) # range type object
# print (v_r)
# print (list(v_r)) # trying to convert a range object to list (type casting). for type casting we have used list() function.
################# for loop ##############

for a in v_r: # for is a reserved keyword. in is a operator
    print(a)
print ("Hi")

In [5]:
v_r1 = range(5,11)
# for a in v_r1: # for is a reserved keyword. in is a operator
#     print(a)
#     print ("Hi") # for each element of the sequence the loop will iterate, loop will iterate means whatever you will write inside a loop that will execute.
# v_r2 = range(11)
# for a in v_r2:
#     print(a)

Name = 1234 # for loop also iterate over string object
for a in Name:
    print("Hi")
# num = "456" # for loop also iterate over string object
# for a in num: # for loop does not iterate over numbers
#     print(a)
#     print("Hi")
# l1 = [2,5,1,7,89] # iterable objects: range object, string, collections
# for a in range(5): # iteraing on range object
#     print(l1[a])
# for a in l1: # iterating on directly on the list object
#     print(a)
data = {1: "palash", 2: "john", 3: "hemangee"}

for v in data.keys(): # we can iterate on keys, values or by default is keys
    print(v)
    print(data[v])

1
palash
2
john
3
hemangee


In [30]:
######## break, continue ##########
# fruits = ["apple", "orange", "banana", "cherry", "mango"]

# for  x in fruits: # iterable object is list, so for every element of the list loop iterates
#     if (x == "banana"): # == is a conditional operator, it does not store a value
#         #break # break is used to stop/terminate the immediate loop
#         continue # continue will skip the present iteration
#     print("I love "+x)
  
    
# print ("Done "+ x)

l2 = [2,5,6,10,11]
for i in l2:
    if i in [5,6]:
        continue
    print(i)

2
10
11


In [ ]:
############ Using a temporary variable #############################
# values = ["palash", 35, 56.8]
# temp = values[2] ### 56.8
# values[2] = values[0] ## palash
# values[0] = temp  ### 56.8
# print(values)
##################### without using a temporary variable ############
# values = ["palash", 35, 56.8]
# print(values)
# values.append(values[2]) #["palash", 35, 56.8, 56.8]
# values[2] =values[0]     #["palash", 35, "palash", 56.8]
# values[0] =values[3]     #[56.8, 35, "palash", 56.8]
# values.pop()             #[56.8, 35, "palash"]
# print(values)

In [33]:
s={22,25,14,21,7,100,300}
print(s) # Doest follow sequence.
s1 = {22,2,14,21,7,258}
print(s1.intersection(s))
c = len(s1.intersection(s))
print(c)
if (c%2==0):
    print("Even")
else :
    print("Odd")

{100, 21, 22, 7, 25, 300, 14}
{14, 21, 22, 7}
4
Even


In [ ]:
########## While loop ############
"""
With while loop we can execute a set of statements as long as a condition is true.

General Syntax

while condition: (the loop ends on the terminating condition)
    statement 1 
    statement 2
"""

# i = 0 # intialization
# while i<10: # it will execute for i=0--->1........9, after that i --->10 (terminating condition)
#     print("i =", i)
#     i+=1 # increament or a decreament i = i+1
# print("done")


# i = 10 # intialization
# while i>0: # it will execute for i=10,9,8,7.....1, after that i --->0 (terminating condition)
#     print("i =", i)
#     i-=1 # increament or a decreament i = i-1
# print("done")


# import time # we have imported this module to get access of the sleep()
# i = 0 # intialization
# while i<10: #  so the condition will always be true ---> infinite loop
#     print(". ", end = " ") # if you want your next print to be printed in same line write end = ""
#     time.sleep(1) # sleep function ---> sending this process to running state to waiting
#     #i = i+1
    
# print("done")

# i = 0
# while i<10:
#     i+=1
#     if i==5:
#         break
#     print(i)

# i = 0
# while i<10:
#     i+=1
#     if i in [2,4]:
#         continue
#     print(i)
############ in while loop we can use else statement ######

# i = 11
# while i<10:
#     print(i)
#     i+=1
# else:
#     print("Unlike other launguages, while can have else")

In [ ]:
########## nested loops ###############

i = 0
j = 0
while i<5:         # i =0--->1--->2--->3---->4      j=0--->1--->2---->3--->4|||| j=0
    print("IITJ")
    while j<5:
        print ("rocks")
        j+=1
    i+=1
    j=0 #### resetting the condition
print("Exit!!!!")


In [ ]:
for i in range(5):   # i= 0,1,.....,4
    print("IITJ")
    for j in range (5): # for each value of i, this loop will execute 5 times
        print("rocks")

In [ ]:
x = [1, 2]
y = [4, 5]

for i in x: # for each value of i both the values of j will be taken
    for j in y:
        print(i,j)

In [7]:
############## Function #################
"""
1. In Python, a function is a group of statements that performs some task. It returns some value at
end.
2. Procedure are similar to functions but it should not returen a value. It only performs the
tasks.
3. In both, we can have parameters.
4. A paremeter is the variables listed inside the parenthesis in the function definition.
5. An argument is the value that is sent to the function when it is called.
6. Function increses the code reusability and reduce the LOC.
"""
def sum_of_two_numbers():#we are creating a new function.def is used to create functin definition
    a = 3
    b = 5
    c = a+b
    print ("the sum is ", c)
    
def sum_of_two_numbers1(a, b):  # parameters are catching the valures based on the positions
    print ("the sum is ", a+b) # inside the function, we are printing the values
    
def sum_of_two_numbers2(a, b): # we are throwing the result
    return a*b

sum_of_two_numbers() # we are calling the function
sum_of_two_numbers()
sum_of_two_numbers()

sum_of_two_numbers1(2,3) # while calling the function, we pass arguments
sum_of_two_numbers1(3,4) # throwing the value
sum_of_two_numbers1(4,5)

print("the mul is ",sum_of_two_numbers2(12,13))
result = sum_of_two_numbers2(13,14) # results = 27
print ("the mul is ", result)
#sum_of_two_numbers2(14,15)    

the sum is  8
the sum is  8
the sum is  8
the sum is  5
the sum is  7
the sum is  9
the mul is  156
the mul is  182


In [38]:
def my_details (name, age, loc = "Delhi"): #user-defined function. You can also create default value
    print("My name is: ", name)
    print("My age is: ",age)
    print("My location is: ", loc)

my_details (age = 35, name = "palash")  # here the arguments are keyword-based

My name is:  palash
My age is:  35
My location is:  Delhi


In [ ]:
####### Another Example (passing list parameter) ##########

def check_even (full_list): # function definition
    even_found = [] # empty list
    for nums in full_list: # every elemnts will checked
        if nums % 2 == 0:  # checking whether it is divisible by 2 
            even_found.append(nums) # if divisible add it to the empty list
        else:
            pass # do nothing
    return even_found

limit = int (input("Please enter the upper limit for natural numbers: ")) #typecasting
# input function is used to take user input and it return string object.

natural_number = list(range(1,limit+1)) # typecasting range object----> list object
print(natural_number)
print(check_even(natural_number))
print(check_even([20,30,100,3,5,8]))

In [ ]:
######## variable number of arguments (dynamically) #########

# def my_mul_add(*args): # function defination of a user defined function
#     i = 0
#     mul = 1
#     while (i<len(args)): ####### i=0, len(args)---->4
#         mul = mul * args[i] ### i=0--> mul = 1 * 10,i=1--> mul = 10 * 12,i=2--> mul = 120 * 3
#                             ### i=3--> mul = 360 * 4
#         i+=1
#     print ("The mul result is: ", mul)
#     return sum(args) # I have used a library func (sum)

# print("The sum is: ",my_mul_add(10,12,3,4)) # I have called the function

# def my_key_value(**kvp):
#     #print("The collection is: ", kvp)
#     for a in kvp:
#         print(kvp[a], end=" ")

# my_key_value(name = "Palash", age=35, loc = "Kolkata") 
# you can pass any number of key-value pairs.



In [8]:
####################### Nested Functions ##########################

def i_am_outsider():
    print ("I am the outsider function")
    def i_am_insider(): # insider function
        print("I am the inner function")

    i_am_insider() # call is ok. Why? Because we are calling from inside the function
    i_am_insider()
    
    
    
i_am_outsider()
i_am_insider() # out of scope can not be called



I am the outsider function
I am the inner function
I am the inner function


NameError: name 'i_am_insider' is not defined

In [ ]:
########### Lambda Function ############
"""
1. Python Lambda functions are anonymous functions which means that the functions are without name
2. Lambda keyword is used to create such function.
Syntax:
lambda arguments: expression 
5. Multiple arguments can be there.
6. Single line.
"""
# a = 10
# # l_func = lambda a: a+10
# # l_func1 = lambda b: b*9
# # print (type(l_func))
# # print(type(a))
# # l_func(100)
# # l_func1(100)
# aa1 = lambda a,b: (a+b, a*b)

# print("the answer is:", aa1(10,30)[1])

In [ ]:
# def is_even(n):
#     if (n%2==0):
#         a = n
#     else:
#         a = False
#     return a

# nums = [2,3,4,5,6,7,8]
# evens = list (filter(is_even, nums)) # filter-->library function

# print(evens)

nums = [2,3,4,5,6,7,8]
evens = list (filter(lambda n: n%2==0, nums)) # filter-->library function

print(evens)

In [13]:
####### Object oriented Programming (OOPs) ###########
"""
1. Class has properties + behaviour.
Properties-----> variables or attributes.
Behaviour ------> Methods/functions.

What is a class?
A class can be considered as a template definition of the methods and variables in a particular kind of object. 
It is a blueprint for an object.

What is object?
Objects are the instances of a particular class.

The roles of a costructor (it is a special function) is

    1. creating a object.
    2. intializing the attributes.
Constructors are called by the class name.
"""
# class computer:
#     def config(self):
#         print("i5 16GB 1 TB");

# c1 = computer();
# # config() # you can not directly call this. Why?
# c1.config(); # behind the scene-----> computer.config(c1)
# computer.config(c1);
# print(type(c1));
# name = "Palash"
# print(type(name));


class student: # keyword class. Class always has a special function----> Constructor
    
    def __init__(self, name, roll, marks): # Attributes are the properties. inint is a special method.
        self.name = name
        self.roll = roll
        self.marks = marks
    
    def print_data(self):
        print("The student's name is :", self.name)
        print("The student's roll is :", self.roll)
        print("The student has obtained:", self.marks)
        print("--------------------")
        
stud1 = student ("palash", 1, 85) # Calling Constructor by the class name
stud2 = student ("John", 2, 95)   # object creation
#stud3 = student ("aa", 3, 75) 
stud1.print_data()
stud2.print_data()
print_data()

i5 16GB 1 TB
i5 16GB 1 TB
<class '__main__.computer'>
<class 'str'>


In [14]:
class student:
    
    def __init__(self):
        self.name ="palash"
        self.roll = 1
    def show(self1):
        a=10
        print("The name is: ", self1.name)
        print("the Roll is:", self1.roll)
        print(a)
a=20    
s1 = student() # we are making the object and default constructor is getting called
s2 = student()
# print(id(s1))
# print(id(s2))
s1.show()
print(a)
# s2.name = "John"
# s2.show()
# student.show(s1)

The name is:  palash
the Roll is: 1
10
20


In [1]:
###### Comparing two objects ######
class student:
    
    def __init__(self):
        self.name = "palash"
        self.roll = 3
        
    def update(self):
        self.roll =36
        
    def compare(self,obj1):
        if self.roll== obj1.roll:
            return True
        else:
            return False
        
s1 = student()
s2 = student()

s1.update()

if s1.compare(s2):
    print("They are same")
else:
    print("they are not same")

they are not same


In [2]:
####################### Types of variables ##########
"""
1. class variable: They are shared across all objects.
2. Instance variable: These are the variables unique to each instance/object.

"""

class bike:
    wheels = 2 #class variable
    
    def __init__(self):
        self.cc = 350
        self.topspeed = 120
        
    def show_details(self):
        print("My cc is :", self.cc)
        print("My topspeed is :", self.topspeed)
        print("The number of wheels: ", self.wheels)
        print("------------------")
b1 = bike()
b2 = bike()
b1.show_details()
b2.show_details()
b2.cc = 150

bike.wheels = 3

b1.show_details()
b2.show_details()

My cc is : 350
My topspeed is : 120
The number of wheels:  2
------------------
My cc is : 350
My topspeed is : 120
The number of wheels:  2
------------------
My cc is : 350
My topspeed is : 120
The number of wheels:  3
------------------
My cc is : 150
My topspeed is : 120
The number of wheels:  3
------------------


In [6]:
############################ Type of methods ##############################
"""
1. Instance methods: Deals with the instance variables of the objects.
2. Class methods: Deals with the class variables and can be called on class itself
3. Static methods: Normally do not deals with the class variables/instance variable. Generic/isolated
   operations can be implemented.
"""

class Student:
    
    college = 'IITJ'
    
    def __init__(self, m1,m2,m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    def avg(self):          # instance method as we are passing self--> means it belongs to some object
        return (self.m1+self.m2+self.m3)/3
    @classmethod #2 imp words in one!
    def get_college_name(cls): # Class methods --> deals with the class variables, no self (as we are not dealing with obj)
        print("The college is :", cls.college)   # cls refers to class here
    @staticmethod
    def info():             # no self, no cls--> make it blank for the static methods, i.e, no parameters
        print("This is a student class.......")
        
s1 = Student(23,24,25) # constructor
s2 = Student(35,36,37)

print(s1.avg())
print(s2.avg())

print(Student.avg(s1)) # you can pass object as paramenter.


Student.info()
s1.info()

24.0
36.0
24.0
This is a student class.......
This is a student class.......


In [7]:
class dog:
    
    def __init__(self):
        self.a = 20
        
    def show_data(self):
        print(self.a)
        
class cat:
    
    def __init__(self):
        self.b = 30
        
    def show_data1(self):
        print(self.b)
        d1 = dog()
        print(d1.a)
        
# d1 = dog()
c1 = cat()

# d1.show_data()
c1.show_data1()

30
20


In [8]:
########################### inner class ####################

class Student1:
    
    def __init__(self, name1, roll1):
        self.name = name1
        self.roll = roll1
        self.lap = self.Laptop()
        
    def show(self):
        print(self.name, self.roll, self.lap.brand, self.lap.cpu, self.lap.RAM)
        
    class Laptop:
        
        def __init__(self):
            self.brand = 'Dell'
            self.cpu ="i5"
            self.RAM = 8
            
s1 = Student1("Palash", 1)
s2 = Student1("John", 2)
s1.show()
s2.show()

lap1 = Student1.Laptop()#u can also create an object of inner class outside the outer class but u need outer class name to call
print(lap1.RAM)
lap1.RAM = 16
print(lap1.RAM)

Palash 1 Dell i5 8
John 2 Dell i5 8
8
16


In [12]:
################## Inheritance #####################
"""
1. Single-level inheritance. (Parent--->child, Super---> sub)
2. Multi-level inheritance.  (Grand Parent---> Parent----> child)
3. Multiple inheritance.     (Multiple parent class)

"""
################ Single level inheritance ########################

class A:
    
    def property1(self):
        print ("I am property 1 from class A")

    def property2(self):
        print ("I am property 2 from class A")

class B (A): #B inherits A
    
    def property3(self):
        print ("I am property 3 from class B")

    def property4(self):
        print ("I am property 4 from class B")
        
b = B()
b.property1()
b.property2()
b.property3()
b.property4()
print("-------------------------------")
a = A()
a.property1()
a.property2()
a.property3()     # error child's property is not there in parent.
a.property4()     # error child's property is not there in parent.

I am property 1 from class A
I am property 2 from class A
I am property 3 from class B
I am property 4 from class B
-------------------------------
I am property 1 from class A
I am property 2 from class A


AttributeError: 'A' object has no attribute 'property3'

In [13]:
#################### Constructors in inheritance #####################
class A:
    
    def __init__(self):
        print("In A's Constructor")
    
    def property1(self):
        print ("I am property 1 from class A")

    def property2(self):
        print ("I am property 2 from class A")

class B (A):
    
#     def __init__(self):      # If b's constructor is not present and A's is present then A's constructor will be called.
#         print("In B's Constructor")

    def __init__(self):
        super().__init__()    # Using super(), you can call super class methods + constructor.
        print("In B's Constructor")
        
    def property3(self):
        print ("I am property 3 from class B")

    def property4(self):
        print ("I am property 4 from class B")

#a1 = A()
b1 = B()
b1.property1()

In A's Constructor
In B's Constructor
I am property 1 from class A


In [16]:
####### Anonther example of single-level inheritance ##############
class trainee:
    
    def __init__(self, tid): 
        self.trainee_id = tid
        
    def show_details_t(self):
        print("Trainee's id is :", self.trainee_id)
            
class manager(trainee): 
    def __init__(self, mgr_id, tid):
        super().__init__(tid)
        self.mgr_id=mgr_id
        
    def show_details_M(self):
        print("Trainee's id is :", self.trainee_id)
        print("Manager's id is :", self.mgr_id)
         
    
t = trainee (23)  
m = manager(20, 1)        # Object construction brings some properties from parent class

m.show_details_M()
m.show_details_t()
t.show_details_t()
# t.show_details_M()       # error child's property is not there in parent.

Trainee's id is : 1
Manager's id is : 20
Trainee's id is : 1
Trainee's id is : 23


In [ ]:
################ Multi-level inheritance ########################

class trainee:
    
    def __init__(self, tid): 
        self.trainee_id = tid
        
    def show_details_t(self):
        print("Trainee's id is :", self.trainee_id)

class project_lead(trainee):
    
    def __init__(self, pid, tid):
        super().__init__(tid)
        self.p_id = pid
        
    def show_details_p(self):
        print("Trainee's id is :", self.trainee_id)
        print("Project_lead's id is :", self.p_id)

class manager(project_lead):
    
    def __init__(self, mgr_id, pid, tid):
        super().__init__(pid, tid)
        self.mgr_id = mgr_id
        
    def show_details_M(self):
        print("Trainee's id is :", self.trainee_id)
        print("Project_lead's id is :", self.p_id)
        print("Manager's id is :", self.mgr_id)
         
    
#t = trainee (23)  
m = manager(20, 1, 2)        # Object construction brings some properties from parent class
p = project_lead(4,5)
m.show_details_M()
print("----------")
m.show_details_p()
print("----------")
m.show_details_t()
p.show_details_M()         # error child's property is not there in parent.
# t.show_details_M()       # error child's property is not there in parent.

In [17]:
################ Multiple inheritance ########################

class trainee:
    
    def __init__(self, tid): 
        self.trainee_id = tid
        
    def show_details_t(self):
        print("Trainee's id is :", self.trainee_id)

    def test(self):
        print("Test from trainee", self.trainee_id)
        
class project_lead:
    
    def __init__(self, pid):
        self.p_id = pid
        
    def show_details_p(self):
        print("Project_lead's id is :", self.p_id)
    
    def test(self):
        print("Test from project_lead", self.p_id)

class manager(trainee, project_lead):
    
    def __init__(self, mgr_id, pid, tid):
          super().__init__(tid)
          project_lead.__init__(self, pid)
          #self.p_id = pid
          self.mgr_id = mgr_id
          super().test() # Method resolution order
          project_lead.test(self)
        
    def show_details_M(self):
        print("Trainee's id is :", self.trainee_id)
        print("Project_lead's id is :", self.p_id)
        print("Manager's id is :", self.mgr_id)
         
    
#t = trainee (23)  
m = manager(20, 1, 2)        # Object construction brings some properties from parent class
p = project_lead(55)
m.show_details_M()
print("------------")
m.show_details_p()
print("------------")
p.show_details_p()
print("------------")
#p.show_details_M()        # error child's property is not there in parent.

Test from trainee 2
Test from project_lead 1
Trainee's id is : 2
Project_lead's id is : 1
Manager's id is : 20
------------
Project_lead's id is : 1
------------
Project_lead's id is : 55
------------


In [ ]:
################ Polymorphism ###################################
"""
1. Polymorphism: Poly ----> many, morph ----> forms.
2. Four ways to implement polymorphism are:

        a. Duck Typing.
        b. Operator Overloading.
        c. Method Overloading.
        d. Method Overriding.
"""

In [ ]:
################ Duck Typing ####################################
"""
1. Duck typing is a concept related to dynamic typing, where the type or the class of an object is less important than 
the methods it defines.

2. When you use duck typing, you do not check types at all. Instead, you check for the presence of a given method or attribute.

Analogy: If a bird walks like a duck, quacks like a duck, swims like a duck, we call that bird a duck.
"""
class Sublime:
    
    def execute(self):
        print("Highlight text using color code")
        print("Compile")
        print("Run")
     
class Jupyter:
    
    def execute(self):
        print("Highlight text using color code")
        print("Spell check")
        print("Provide Cells")
        print("Compile")
        print("Run")
        
class Computer:
    
    def program (self, IDE): # Dynamic typing of object, you can replace object type provided 
         IDE.execute()       # execute method should be there. We only see the behaviour
                             #(execute()) and we think its an IDE. May be a dog class  
                             #can have execute but thats not and IDE. But we don't care.
                 
i1 = Sublime() # Object of sublime class
i2 = Jupyter() # Object of Jupyter class


sys1 = Computer()
sys1.program(i3)

In [ ]:
######################## Operator Overloading #############################
"""
1. Operator Overloading means giving extended meaning beyond their predefined operational meaning.
2. You might have noticed that the same built-in operator or function shows different behavior for
objects of different classes, this is called Operator Overloading. 
3. The method name is the same, but the type of arguments and number of arguments change. 
"""
class student:
    
    def __init__ (self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, obj):
        m1 = self.m1 + obj.m1
        m2 = self.m2 + obj.m2
        s3 = student(m1, m2)
        return s3

#     def __sub__(self, obj):
#         m1 = self.m1 - obj.m1
#         m2 = self.m2 - obj.m2
#         s3 = student(m1, m2)
#         return s3
    
#     def __mul__(self, obj):
#         m1 = self.m1 * obj.m1
#         m2 = self.m2 * obj.m2
#         s3 = student(m1, m2)
#         return s3
    
    def show(self):
        print (self.m1, self.m2)
        
s1  = student (22, 44)
s2  = student (4, 5)

s3 = s1 + s2

# s4 = s1 - s2
# s5 = s1 * s2

s3.show()
# s4.show()
# s5.show()

In [ ]:
######################## Method Overloading #############################
class Student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
#     def sum (self, a, b):
#         return a+b

    def sum (self, a, b, c):
        return a+b+c
             
#     def sum (self, a = None, b = None, c = None):
#         s = 0
        
#         if a!=None and b!=None and c!=None:
#             s = a+b+c
#         elif a!=None and b!=None:
#             s = a+b
#         else:
#             s = a
        
#         return s

s1 = Student (5, 6)
print(s1.sum(2,3,7))

In [ ]:
######################## Method Overriding #############################

class A:
    
    def show (self):
        print("I am show from class A")
        
class B(A):
      #pass
    def show (self):
        print("I am show from class B")
        
o = B()
o.show()

In [ ]:
######### Array in python #########
"""
1. Arrays are collection of homogeneous datatypes.
2. Types: i-->signed int, I --> unsigned int, f---> float, d--->double, L ---> unsigned Long, l ---> signed long, 
u--->char.
"""
from array import *               # By default arrays are not supported, you need to import the array module.

vals = array('i', [1,2,3,4,5])
vals1 = array('i', [1,2,3,4,6]) # Heterogenous data not supported
#vals = array('I', [1,2,3,-4,5])  # Signed int, both positive and negative values are supported
# vals1 = array('i', [1,2,3,-4,5])
val3 = vals+vals1                # not getting elementwise sums. One is appended with other. Elementwise sum in numpy.         
print(val3)
# #vals = array('I', [1,2,3,-4,5]) # Unsigned int, negative value not supported
c = array('u', ['A','B', 'C'])   # u (unicode) --> charecters
# print(vals)
print(vals.buffer_info()) # Returns a tuple with initial address of the array with the number of elements.
print(vals.typecode)      # Returns the typecode of the array i.e. i, I, B , etc.
vals.reverse()             # Reverse does not return any value. This only reverses the whole array.
print(vals)
print(c[0])

In [ ]:
#################### How to print array elements one by one #############
from array import *  
vals = array('i', [11,21,31,-4,5])

# for i in range(len(vals)):         # this works   
#     print(vals[i])

# for i in vals:             # this works 
#     print(i)

# i = 0                      # this also works
# while i<len(vals):
#     print(vals[i])
#     i+=1

In [ ]:
############Coping one array to other #####################
from array import * 
vals = array('i', [1,2,3,-4,5])

newarr = array(vals.typecode, (a*2 for a in vals)) # copied double of each number
print(newarr)

In [ ]:
############### User input to an array #####################

from array import *

arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)
    
print(arr)

In [ ]:
############# Searching an element in the array ########################
from array import *

arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)
    
Key = int(input("Enter the value to be searched "))
k = 0
for item in arr:
    if item==Key:
        print("Item found on ", k)
        break
    k+=1
    
print("Item found on ", arr.index(Key))

In [ ]:
! pip3 install numpy


In [ ]:
####################### numpy ############################
"""
1. Helps in dealing with multi-dimensional array.
2. This does not come with the default packages of python. We need to install it separately.
3. Use "! pip3 install numpy" to install numpy.
"""
from numpy import *

vals = array([1,2,3,-4,5.6]) # typecode is not mandatory.
vals1 = array([1,2,3,-4,5.6], float) # Explicit Conversion  
print(vals)
print(vals1)

In [ ]:
############ More on arrays #################
"""
--> Arrays can be made by array(), linspace(), logspace(), arange(), zeros(), ones().....
--> NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
"""

from numpy import *
arr = array ([1,2,3,4,5])
# print(arr)
print(arr.dtype) # datatype of the values
# arr1 = array ([1,2,3,4.8,5]) # implicit conversion
# print(arr1) # Every value here will be converted into float
# print(arr1.dtype)
# arr2 = array ([1,2,3,4,5], float) # Explicit conversion
# print(arr2)
# arr3 = array ([1.2,2.3,3.1,4.2,8.3], int) # Explicit conversion
# print(arr3)


# arr = linspace(0,15,25) # Parameters are start, stop, parts. Default step is 50. As it is step values are by default float here.
# #arr[1] = 3
# print(arr)

arr1 = arange(0,15,2) # Parameters are start, stop, steps. Here, it is step not a part.
#arr1[1] = 3
print(arr1)

# arr1 = zeros(15, int) # Array of size 15. All are initialized to 0s. By default, the  values are float.
# #arr1[1] = 3
# print(arr1)

# arr1 = ones(15, int) # Array of size 15. All are initialized to 1s. By default, the  values are float.
# #arr1[1] = 3
# print(arr1)


# arr = logspace(1,40,5)#Array will be devided into 5 parts. Start: 10^1 end: 10^40. The start to end will be divided into 5 parts.  
# #arr[1] = 3
# print(arr)
# print('%.2f' %arr[1])

In [ ]:
################## More Operations on array #######################
from numpy import *
arr = array([1,2,3,4,5])
arr1 = array([1,2,3,4,5])
arr2 = zeros(5, int)
# Want to add a number with each element of the array #######

# ##### 1st approach #######

# for i in range(len(arr)):
#     arr[i] = arr[i] + 5
    
# print(arr)

# ##### 2nd approach ######
# arr = arr + 10
# print(arr)


# Want to add 2 arrays #######

##### 1st approach #######

for i in range(len(arr)):
    arr2[i] = arr[i] + arr1[i]
    
print(arr2)

# ##### 2nd approach ######
arr3 = arr + arr1 ### Vectorized Operation (Was getting appended without numpy right?)
print(arr3)

In [ ]:
############# Mathemetical operations ################
from numpy import *
arr = array([1,2,3,4,5])
arr1 = array([6,7,8,9,10])
print(sin(arr)) ###### Sin values of each element ###########
print(cos(arr)) ###### Cos values of each element ###########
print(log(arr)) ###### log values of each element ###########
print(sqrt(arr)) ####### sqrt values of each element #########
print(sum(arr))  ########## sum of each element #############
print(min(arr))  ########## min of each element #############
print(max(arr))  ########## max of each element #############
arr3 = concatenate([arr, arr1])
print(concatenate([arr, arr1])) ########## Concatenating two arrays #############
print(arr3) ########## Concatenating two arrays #############

In [1]:
################## Coping one array to other ####################
"""
Three types of copies-
                    1. Aliasing.
                    2. Shallow Copy.
                    3. Deep Copy.
"""
from numpy import *
arr = array([1,2,3,4,5])
# arr2 = arr             # Only Aliasing 
# print(arr2)
# print(id(arr), id(arr2)) #In memory, we have only one instance of each element. Only duplicate reference variables are created.

# arr3 = arr.view() # shallow copy ---> changing in one affects the other. 
# arr[1] = 90
# print(arr)
# print(arr3)
# print(id(arr), id(arr3)) # Addresses are different i.e. two copies of each elements are now created.


arr3 = arr.copy() # deep copy ---> changing in one does not affect the other. 
arr[1] = 90
print(arr)
print(arr3)
print(id(arr), id(arr3))

[ 1 90  3  4  5]
[1 2 3 4 5]
1468521791376 1468522185232


In [6]:
################### Working with matrix in python ##############################
from numpy import *

arr1 = array([
            [1,2,3,7,8,9],
            [4,5,6,99,88,77]
            ])

print (arr1)
print (arr1.dtype) # Data type
print (arr1.ndim)  # Number of dimension 
print (arr1.shape) # (rows, cols)
print (arr1.size)  # total number of elements

arr = arr1.flatten() # Convert the 2D array into 1D array
print(arr)

arr3  = arr.reshape(3,4) # 3 rows 4 cols -----> Converting 1D array to 2D array
print (arr3)
print ("----------------")
arr4  = arr.reshape(3,2,2) # 3 dim 2 rows 2 cols -----> Converting 1D array to 2D array
print (arr4) 

[[ 1  2  3  7  8  9]
 [ 4  5  6 99 88 77]]
int32
2
(2, 6)
12
[ 1  2  3  7  8  9  4  5  6 99 88 77]
[[ 1  2  3  7]
 [ 8  9  4  5]
 [ 6 99 88 77]]
----------------
[[[ 1  2]
  [ 3  7]]

 [[ 8  9]
  [ 4  5]]

 [[ 6 99]
  [88 77]]]


In [8]:
############## Working with matrices #####################

from numpy import *

arr1 = array([
            [1,2,3,7],
            [4,5,6,9]
            ])

m = matrix(arr1)  # Converting a 2D array into a matrix format
m1 = matrix ('1 2 3;4 5 6;7 8 9') # Converting a string into a matrix format (even this works)
print(m) # Output is same but with this conversion, you can do planty of additional oprations.
print(m1)
print(diagonal(m1)) # print the diagonal elements of the matrix
print(m1.min()) # Finding Minimum of a matrix
print(m1.max()) # Finding Maximum of a matrix

[[1 2 3 7]
 [4 5 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
1
9


In [9]:
############## Working with matrices #####################
from numpy import *
m = matrix ('1 2 3;4 5 6;7 8 9')
m1 = matrix ('1 2 3;4 5 6;7 8 9')

m3 = m+m1
m4 = m*m1

print("The result matrix is \n", m3)
print("The result matrix is \n", m4)

The result matrix is 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
The result matrix is 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
from numpy import *
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))

mat = []
mat1 = []
print("Enter the entries rowwise:")

for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    mat.append(a)
m = matrix(mat)

for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    mat1.append(a)
m2 = matrix(mat1)

for i in range(R):
    for j in range(C):
        mat[i][j] = mat[i][j] + mat1[i][j]
m = m + m2
print("The sum is = \n")
for i in range(R):
    for j in range(C):
        print(mat[i][j], end = " ")
    print()
    
print("---------------")
print("The sum is = \n")
print(m)

In [ ]:
######### Iterator #####################
"""
1. Iterator is an object that contains the countable number of values. Iterator in Python is simply an object that can be 
iterated upon. An object which will return data, one element at a time.
"""
##### We have seen this #####
nums = [1,8,9,0]

# for i in nums:
#     print(i)      # This iterates over the list and prints the values....
    
####### Alternatively we can also use an iterator object ##########

itt = iter (nums)
print(itt) #### It prints the object itself

####### want get the values ######
print(itt.__next__()) #### here we do not have to use the index values
print(itt.__next__()) ### next will always give you the next value. It always knows the last value and return the next. 
print(next(itt)) ### this also works..


In [ ]:
######## Can we have our own iterator object ###########
"""
1. Previous iterator object is made and returned by the in-built function i.e. iter().
2. Can we make our own iterator object? Yes for that, we need to design our own class.
3. A python iterator object must implement two special methods,  __iter__() and __next__().

"""

class Topfive:
    
    def __init__(self): # Helps in setting the initial value
        self.num = 1
        
    def __iter__(self): # return the iterator object. Helps to make the object of the class, behave like an iterator
        return self
    
    def __next__(self): # Next method returns the next item in the sequence. On reaching end, it must raise StopIteration 
        if self.num <= 5:
            val = self.num
            self.num += 1
            return val
        else:
            raise StopIteration ###### raise exeception to stop the for loop
    
values = Topfive() #### Once the object of topfive is created, it behaves like an iterator.


print(values.__next__()) #### without index, you can get the next values in sequence.

# for i in values:
#     print(i)


In [ ]:
###################### Generator in python #########################
"""
1. So in iterators, we need to define two functions __iter__() and __next__(). If you want Python to do all for us,
you can use generators.
2. The generators will give you the iterators.
3. How can we use generators?
"""

# def topfive():#Converting this function into a generator by a special keyword called yield, normally we have return in func.
#     yield 5   # Generators primarily have yield instead of return
    
# val = topfive() # So topfive is a generator function which is returning the iterator object

# print(val.__next__()) ## So on iterator __next__() will work.
# print(val.__next__()) # one value is there in the generator----> so throwing an exception.   

# def topfive():#Converting this function into a generator by a special keyword called yield, normally we have return in func.
#     yield 5
#     yield 6
    
# val = topfive()

# print(val.__next__())
# print(val.__next__()) # no error now. For loop can also be used to fetch the values from iterator.


##### How to create generator that returns multiple values ##########################
def topfive(): # Generator function having a yield
    
    n = 1
    
    while n <= 5:
        yield n    # Yield does not terminates a function like return does. It will continuously send values. 
        n+=1
        
values = topfive()

for i in values:
    print(i)

In [ ]:
####### Imperative vs Declarative programming ############
"""
1. Imperative Programming as the name suggests is a type of programming paradigm that describes how the program executes. 
Developers are more concerned with how to get an answer step by step. This includes procedural programming (Procedural: Tasks are treated as step-by-step 
iterations where common tasks are placed in functions that are called as needed. ), object-oriented programming,
parallel processing approach.  

2. Declarative Programming as the name suggests is a type of programming paradigm that describes what programs to be 
executed. Developers are more concerned with the answer that is received. This includes logic programming and functional
programming.  
"""

####### Example of Imperative and Declarative programming ############### 

# Imperative approach to find the sum of a list

# l1 = [1,33,4,5]
# total = 0
# for item in l1:
#     total += item
# print(total)

# Declarative approach to find the sum of a list

l1 = [1,33,4,5]
print(sum(item for item in l1))
#print(sum(l1))