In [1]:
# !pip install numpy

In [37]:
import numpy as np

## Basic Intro
- All of the elements in a NumPy array should be homogeneous,i.e, of same datatype, unlike a list.
- An array is a central data structure of the NumPy library,it's a grid of values and it contains information about the raw data.
- Rank: number of dimensions
- Shape: gives us size along each dimension
- Vector: 1D array
- Matrix: 2D array
- Tensor: array with 3 dimensions or above. Note that dimensions are often called as axes.

In [3]:
# Creation of an array
a=np.array([1,2,3,4]) # np.array(prev created list_name OR type out the list here itself)
a

array([1, 2, 3, 4])

In [4]:
#dont create arrays with different number of columns

In [5]:
b=np.zeros((2,2),dtype=int)
b

array([[0, 0],
       [0, 0]])

In [6]:
c=np.ones((2,2))
c

array([[1., 1.],
       [1., 1.]])

In [7]:
c.ndim #prints out the number of dimensions, note that there is no ()

2

In [41]:
np.identity(3,dtype=int) #identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
string_array=np.array(['1.2','-2.4','3.5','15.7'])
string_array.astype(float)

array([ 1.2, -2.4,  3.5, 15.7])

In [48]:
#temporary change
string_array

array(['1.2', '-2.4', '3.5', '15.7'], dtype='<U4')

In [45]:
int_array=string_array.astype(int) #can't convert floating point values inside string to int type
int_array

ValueError: invalid literal for int() with base 10: '1.2'

In [8]:
np.random.random(3)

array([0.09849631, 0.91055965, 0.98868856])

In [9]:
np.random.random((3,3))

array([[0.40241441, 0.17154265, 0.44178456],
       [0.51615879, 0.14056878, 0.85635933],
       [0.24726774, 0.47790534, 0.18583495]])

In [10]:
np.random.rand(2)

array([0.40584711, 0.90043062])

In [11]:
np.random.rand(4,2) #all entries are between (0,1) and no need of further paranthesis

array([[0.1511869 , 0.4720602 ],
       [0.29700102, 0.90428921],
       [0.69500111, 0.53890798],
       [0.29223643, 0.96023926]])

In [12]:
np.random.rand(2,4,4) #2 sets of 4x4 matrices, all entries are between (0,1)

array([[[0.22966606, 0.76533343, 0.12563552, 0.88657014],
        [0.67435165, 0.34905772, 0.47155034, 0.73375164],
        [0.2258357 , 0.75207255, 0.97145535, 0.44648773],
        [0.00180474, 0.78555101, 0.97907028, 0.25971021]],

       [[0.85435629, 0.65766028, 0.38779782, 0.46422533],
        [0.55788199, 0.62702751, 0.77294712, 0.61548462],
        [0.60795041, 0.72049389, 0.82301471, 0.87610011],
        [0.94215229, 0.92564374, 0.17225757, 0.33561918]]])

In [13]:
np.random.randn(3,3) #random numbers in 3x3 with both +ve and -ve numbers

array([[-0.11896848,  0.59978958,  0.09762387],
       [ 1.00423736, -1.88449042,  1.42069464],
       [ 1.18138685, -0.74981485,  0.16812407]])

In [14]:
np.random.randint(4) #random non negative integer less than 4

0

In [15]:
np.random.randint(1,5) #any number from [start, stop), not rxc &also without paranthesis 

4

In [16]:
np.random.randint(4,size=(3,3)) #till 3 only

array([[2, 2, 1],
       [2, 3, 0],
       [1, 2, 1]])

In [17]:
np.random.randint(4,10,size=(3,3)) #from 4 till 9 only

array([[5, 5, 4],
       [5, 4, 4],
       [9, 4, 7]])

In [18]:
list_name=['One','Two','Three','Four']
np.random.choice(list_name, size=(2,2)) #to choose from the given list as parameter

array([['Two', 'Four'],
       ['One', 'Four']], dtype='<U5')

In [19]:
np.random.choice(list_name, size=(2,2), p=[0.9,0.05,0.025,0.025]) 
#we can further add probabilities for the occurence of each of the elements in our list, make sure
#it is a list and has elements of the same number as that of the original list
#also ensure that sum of individual probabilities sum up to 1

array([['One', 'One'],
       ['One', 'One']], dtype='<U5')

In [20]:
np.random.normal(2,4,size=(2,3,4)) #(mean,stdev,size=(r x c x h))

array([[[-1.15921183,  2.75649936,  1.20986782, -2.18181458],
        [ 3.39390038,  3.23217277, 15.70970318,  3.15280985],
        [ 1.12700554,  7.37670742,  1.26344084,  3.29953441]],

       [[-0.14732429, -7.03581807,  6.12025915,  1.07670462],
        [ 0.36364445,  1.78304033,  1.95009775, -3.28100819],
        [-1.61377258,  1.77997441, -0.64557686,  2.27004598]]])

In [21]:
b.trace() #the actual 'trace' in the matrix

0

In [22]:
#Stacking --> hstack and vstack--> enter a tuple as the parameter inside function name
arr1=np.arange(1,5).reshape(2,2)
arr2=np.arange(5,15).reshape(5,2)
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [23]:
arr3=np.random.randint(45,51,size=(2,3))
np.hstack((arr1,arr3))

array([[ 1,  2, 45, 50, 45],
       [ 3,  4, 47, 50, 45]])

In [24]:
d=np.arange(0,6).reshape(2,3)
d

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
e=d>3
e

array([[False, False, False],
       [False,  True,  True]])

In [26]:
d[d>3]

array([4, 5])

In [27]:
# now we are kind of accessing these elements that satisfy the condition, and we can perform
# operations on them too
d[d>3]=0

In [28]:
d[d<=3]=1
d

array([[1, 1, 1],
       [1, 1, 1]])