<h1 style="font-size:50px;color:gray;"><center>Introduction to Numpy</center></h1>

![](http://m.memegen.com/o6i6hi.jpg)

# [RESOURCE](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html)

-----------

# Python Lists vs. Numpy Arrays
![](https://memegenerator.net/img/instances/400x/74259368.jpg)

- **Size** - Numpy data structures take up less space

- **Performance** - they have a need for speed and are faster than lists

- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built-in.

# Installation

```
!pip install numpy
```

![](https://i.stack.imgur.com/gj5ue.jpg)

For example:
```python
[[ 1, 2, 3],
 [ 4, 2, 5]]
```

In [1]:
# !pip list

In [2]:
# !pip install numpy

In [2]:
import numpy as np

In [4]:
list_ = [[1, 2, 3],[4, 5, 6],[4,5,6]]
list_

[[1, 2, 3], [4, 5, 6], [4, 5, 6]]

In [5]:
type(list_)

list

In [6]:
arr = np.array(list_)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [8]:
type(arr) #numpy.n_dimensional_array

numpy.ndarray

In [9]:
arr.dtype #what is the datatype of elements in the array, note that numpy arrays are homogenous
#so same datatype for esch element

dtype('int32')

In [10]:
arr.ndim

2

In [11]:
arr.shape

(3, 3)

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [13]:
arr.T # Transpose

array([[1, 4, 4],
       [2, 5, 5],
       [3, 6, 6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [15]:
arr = arr.T
arr

array([[1, 4, 4],
       [2, 5, 5],
       [3, 6, 6]])

## Array Creation
---
There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the **array** function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [16]:
# import numpy as np

In [17]:
mylist = [[1,2,3],
         [4,5,6]]

In [18]:
arr = np.array(mylist)

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. **For example:** np.zeros, np.ones, np.full, np.empty, np.random.random, np.random.randint etc.

In [20]:
np.zeros((3,3)) # Float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.zeros((4,4), dtype='int')

In [22]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr.dtype

dtype('int32')

In [24]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
a = np.full((3,3), 4)
a

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [26]:
a.ndim

2

In [27]:
np.random.rand(2,3) # (0,1] only

array([[0.55263115, 0.05191634, 0.95973864],
       [0.71159495, 0.1279149 , 0.96670546]])

In [28]:
np.random.randn() #n--> from normal distribution

-0.16638436508584903

In [29]:
np.random.randint(100) # any one value which is < 100 

96

In [30]:
np.random.randint(15, size=(2, 4))

array([[11,  3,  0, 12],
       [10, 12,  1,  8]])

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
   - **arange:** returns evenly spaced values within a given interval. **step** size is specified.
   - **linspace:** returns evenly spaced values within a given interval. **num** no. of elements are returned.

In [31]:
list(range(1,10)) # end number - 1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [33]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
list(range(10))

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [36]:
np.arange(1,10,2.55)

array([1.  , 3.55, 6.1 , 8.65])

In [37]:
np.linspace(1000,9999,20) # 20 values
# Start number is 1000
# 18 numbers
# End number is 9999

array([1000.        , 1473.63157895, 1947.26315789, 2420.89473684,
       2894.52631579, 3368.15789474, 3841.78947368, 4315.42105263,
       4789.05263158, 5262.68421053, 5736.31578947, 6209.94736842,
       6683.57894737, 7157.21052632, 7630.84210526, 8104.47368421,
       8578.10526316, 9051.73684211, 9525.36842105, 9999.        ])

# Array Reshaping
---
We can use **reshape** method to reshape an array. Consider an array with shape (a1, a2, a3, ..., aN). We can reshape and convert it into another array with shape (b1, b2, b3, ....., bM). The only required condition is:   

*a1 x a2 x a3* .... *x aN = b1 x b2 x b3* .... *x bM*

(i.e original size of array remains unchanged.)

In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4,5,6,7,8]])

In [5]:
arr.shape

(1, 8)

In [6]:
arr.ndim

2

In [7]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [12]:
arr.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [10]:
arr.reshape((3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

# Array Flattening
---
We can use **flatten** method to get a copy of array collapsed into **one dimension**. It accepts *order* argument. Default value is 'C' (for row-major order). Use 'F' for column major order.

In [ ]:
# import numpy as np
# faltten ---> mean, median, mode, sum, max, min

In [9]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
arr.sum()

21

In [19]:
arr.min()

1

In [20]:
arr.max()

6

In [21]:
arr.std()

1.707825127659933

# Array Indexing
---
Knowing the basics of array indexing is important for analysing and manipulating the array object.
NumPy offers many ways to do array indexing.

- **Positive tuple indexing**


In [ ]:
# import numpy as np

In [24]:
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [25]:
arr[2]

array([2.6, 0. , 7. , 8. ])

In [ ]:
arr[2][1]

In [26]:
arr[2][1] = 25
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6, 25. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [27]:
arr[2,1]

25.0

In [28]:
arr.shape

(4, 4)

In [29]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6, 25. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [30]:
arr[2][1]

25.0

![](https://i.imgur.com/fzoXLq1.png)

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [31]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6, 25. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [32]:
arr[:2,:2] # end index - 1

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [33]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6, 25. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [34]:
arr[:,:2]

array([[-1. ,  2. ],
       [ 4. , -0.5],
       [ 2.6, 25. ],
       [ 3. , -7. ]])

In [35]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6, 25. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [36]:
arr[2:, :3]

array([[ 2.6, 25. ,  7. ],
       [ 3. , -7. ,  4. ]])

![](https://i.imgur.com/Tr6SAwv.png)

- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [37]:
arr[2][1]=10

In [38]:
# 10 > 20, 1 == 1

In [39]:
arr > 0

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [40]:
# variable_name[condition]
arr[arr > 0]

array([ 2. ,  4. ,  4. ,  6. ,  2.6, 10. ,  7. ,  8. ,  3. ,  4. ,  2. ])

In [43]:
arr[arr < 0]

array([-1. , -0.5, -7. ])

# Array Operations
---
Plethora of built-in arithmetic functions are provided in NumPy.

- **Elementwise operation:** We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

In [ ]:
# import numpy as np

In [44]:
arr = np.arange(1,7).reshape(2,3)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = arr + 1 # Reassignment
arr

- **Unary operators:** Many unary operations are provided as a method of **ndarray** class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.


In [49]:
arr = np.array([[1,9,3],[7,6,2]])

In [50]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [51]:
arr.mean()

4.666666666666667

In [52]:
arr.sum()

28

In [53]:
arr.min(), arr.max()

(1, 9)

In [54]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [55]:
arr.sum(axis=0)
# row index

array([ 8, 15,  5])

In [56]:
arr.sum(axis=1)
# columns

array([13, 15])

In [57]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [58]:
arr.max()

9

In [59]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [60]:
arr.min(axis=0)

array([1, 6, 2])

In [61]:
arr.max(axis = 1)

array([9, 7])

- **Binary operators:** These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, *, etc. In case of +=, -=, *= operators, the exsisting array is modified.


In [3]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

In [4]:
c=a*b #directly multiplication of corresponding elements
c

array([[ 5, 12],
       [21, 32]])

In [5]:
np.matmul(a,b) #matrix multiplication

array([[19, 22],
       [43, 50]])

In [6]:
a@b #matrix multilication

array([[19, 22],
       [43, 50]])

- **Universal functions (ufunc):** NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

**Note:** All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.sum()

21

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
b

array([[5, 6],
       [7, 8]])

In [14]:
a+b

array([[ 6,  8],
       [10, 12]])

In [15]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [16]:
a-b

array([[-4, -4],
       [-4, -4]])

In [17]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [18]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [19]:
a * b

array([[ 5, 12],
       [21, 32]])

In [20]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.cos(arr)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [23]:
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [24]:
np.tan(arr)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [27]:
a = 1.6463
print(a,round(a,2))

1.6463 1.65


# Array Sorting
---
There is a simple **np.sort** method for sorting NumPy arrays.


In [ ]:
# import numpy as np

In [ ]:
a = [1,4,2,4,9,10,2,21,23]
a

In [ ]:
sorted(a) # temporary change

In [ ]:
a

In [ ]:
a.sort() # Permanent change

In [ ]:
a

In [ ]:
# import numpy as np

In [29]:
arr = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [30]:
np.sort(arr)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [31]:
np.sort(arr, axis=1)
# arr = np.sort(arr, axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [ ]:
arr

In [ ]:
np.sort(arr, axis=0)

In [ ]:
arr

In [ ]:
np.sort(arr, axis=None)

In [ ]:
print(-np.sort(-arr, axis = None))

In [ ]:
arr